/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2023  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.utils.bossbar;

import de.steamwar.bausystem.region.Region;
import org.bukkit.boss.BarColor;
import org.bukkit.boss.BarFlag;
import org.bukkit.boss.BarStyle;

public interface BauSystemBossbar {

    String getTitle();
    void setTitle(String title);

    double getProgress();
    void setProgress(double progress);

    BarColor getColor();
    void setColor(BarColor color);

    BarStyle getStyle();
    void setStyle(BarStyle style);

    boolean hasFlag(BarFlag flag);
    void addFlag(BarFlag flag);
    void removeFlag(BarFlag flag);

    boolean isVisible();
    void setVisible(boolean visible);

    Region getRegion();

    void cleanup();
}
