/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2021  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem;

import de.steamwar.bausystem.world.Detoloader;
import de.steamwar.core.VersionDependent;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.util.Vector;

public class FlatteningWrapper {
    private FlatteningWrapper(){}

    public static final IFlatteningWrapper impl = VersionDependent.getVersionImpl(BauSystem.getPlugin());

    public interface IFlatteningWrapper {
        boolean tntPlaceActionPerform(Location location);
        boolean setRedstone(Location location, boolean active);
        Detoloader onPlayerInteractLoader(PlayerInteractEvent event);
        boolean getLever(Block block);

        boolean isNoBook(ItemStack item);

        boolean inWater(World world, Vector tntPosition);
        Material getTraceShowMaterial();
        Material getTraceHideMaterial();
        Material getTraceXZMaterial();

        void giveStick(Player player);
    }
}
