/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2023  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.loader.elements.impl;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.features.loader.elements.LoaderInteractionElement;
import de.steamwar.bausystem.features.loader.elements.LoaderSettingsEnum;
import de.steamwar.inventory.SWItem;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.block.data.Powerable;
import org.bukkit.entity.Player;

import java.util.function.Consumer;

public class LoaderTicks extends LoaderInteractionElement<LoaderTicks.TicksSettingsEnum> {

    private String name;
    private Material material;
    private int ticks;

    public LoaderTicks(Location location, String name, Material material, int ticks) {
        super(location, TicksSettingsEnum.NO_WAIT_FOR, TicksSettingsEnum.NOOP, TicksSettingsEnum.values());
        this.name = name;
        this.material = material;
        this.ticks = ticks;
    }

    public enum TicksSettingsEnum implements LoaderSettingsEnum<Powerable, LoaderTicks, TicksSettingsEnum> {

        NOOP {
            @Override
            public int getPos() {
                return 2;
            }

            @Override
            public SWItem menu(Player player, LoaderTicks parent, int power, long ticks) {
                return new SWItem(Material.STRUCTURE_VOID, translateItemName(parent.name, "LOADER_INTERACTION_NOOP", player));
            }

            @Override
            public void execute(Location location, Powerable blockData, LoaderTicks parent, int power, long ticks, Consumer<Long> delay) {
            }
        },

        NO_WAIT_FOR {
            @Override
            public int getPos() {
                return 5;
            }

            @Override
            public SWItem menu(Player player, LoaderTicks parent, int power, long ticks) {
                return new SWItem(parent.material, translateItemName(parent.name, "LOADER_INTERACTION_NO_WAIT_FOR", player, ticks));
            }

            @Override
            public void execute(Location location, Powerable blockData, LoaderTicks parent, int power, long ticks, Consumer<Long> delay) {
                Powerable powerable = (Powerable) location.getBlock().getBlockData();
                powerable.setPowered(true);
                parent.update(powerable);

                BauSystem.runTaskLater(BauSystem.getInstance(), () -> {
                    powerable.setPowered(false);
                    parent.update(powerable);
                }, parent.ticks);
            }
        },

        WAIT_FOR {
            @Override
            public int getPos() {
                return 6;
            }

            @Override
            public SWItem menu(Player player, LoaderTicks parent, int power, long ticks) {
                return new SWItem(parent.material, translateItemName(parent.name, "LOADER_INTERACTION_WAIT_FOR", player, ticks));
            }

            @Override
            public void execute(Location location, Powerable blockData, LoaderTicks parent, int power, long ticks, Consumer<Long> delay) {
                NO_WAIT_FOR.execute(location, blockData, parent, power, ticks, delay);
                delay.accept((long) parent.ticks);
            }
        }
    }

    @Override
    public SWItem menu(Player player) {
        return new SWItem(material, translateItemName(name, player));
    }

    @Override
    public boolean checkBlockInWorld() {
        return location.getBlock().getType() == material;
    }
}
