/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2022  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.utils;

import de.steamwar.Reflection;
import net.minecraft.network.protocol.game.PacketPlayInFlying;
import net.minecraft.server.level.EntityPlayer;
import org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer;
import org.bukkit.entity.Player;

public class PlayerMovementWrapper20 implements PlayerMovementWrapper {

    @Override
    public void setPosition(Player player, Object object) {
        PacketPlayInFlying packetPlayInFlying = ((PacketPlayInFlying) object);
        EntityPlayer entityPlayer = ((CraftPlayer) player).getHandle();
        if (packetPlayInFlying.h) {
            entityPlayer.b(packetPlayInFlying.a, packetPlayInFlying.b, packetPlayInFlying.c, packetPlayInFlying.d, packetPlayInFlying.e);
        } else {
            entityPlayer.e(packetPlayInFlying.a, packetPlayInFlying.b, packetPlayInFlying.c);
        }
    }

    @Override
    public Object convertToOut(Player player, Object object) {
        PacketPlayInFlying packetPlayInFlying = ((PacketPlayInFlying) object);
        Object packet = Reflection.newInstance(teleportPacket);
        teleportEntity.set(packet, player.getEntityId());
        teleportPosition.set(packet, packetPlayInFlying.a, packetPlayInFlying.b, packetPlayInFlying.c,
                packetPlayInFlying.h ? player.getLocation().getYaw() : packetPlayInFlying.d,
                packetPlayInFlying.h ? player.getLocation().getPitch() : packetPlayInFlying.e);
        return packet;
    }
}
