/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2021  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.region.loader;

import de.steamwar.bausystem.BauSystem;
import org.bukkit.Bukkit;

import java.io.File;
import java.util.logging.Level;

public class Updater {

    private long lastUpdate;

    public Updater(File file, Runnable updaterCode) {
        this.lastUpdate = file.lastModified();
        Bukkit.getScheduler().runTaskTimer(BauSystem.getInstance(), () -> {
            if (file.lastModified() > lastUpdate + 10) {
                try {
                    updaterCode.run();
                    Bukkit.getLogger().log(Level.INFO, "Update complete of " + file.getAbsolutePath());
                } catch (Exception e) {
                    Bukkit.getLogger().log(Level.INFO, "Error while loading file " + file.getAbsolutePath() + " for config: " + e.getMessage(), e);
                }
                lastUpdate = file.lastModified();
            }
        }, 20, 20);
    }

}
