/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2021  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.util.items;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.Permission;
import de.steamwar.bausystem.linkage.specific.BauGuiItem;
import de.steamwar.inventory.SWAnvilInv;
import de.steamwar.inventory.SWItem;
import de.steamwar.linkage.Linked;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.ClickType;
import org.bukkit.inventory.ItemStack;

import java.util.Arrays;

@Linked
public class SpeedBauGuiItem extends BauGuiItem {

    public SpeedBauGuiItem() {
        super(17);
    }

    @Override
    public ItemStack getItem(Player player) {
        return new SWItem(Material.SUGAR, BauSystem.MESSAGE.parse("SPEED_ITEM", player), Arrays.asList(BauSystem.MESSAGE.parse("SPEED_ITEM_LORE", player) + player.getFlySpeed() * 10f), false, clickType -> {
        }).getItemStack();
    }

    @Override
    public boolean click(ClickType click, Player p) {
        p.closeInventory();
        SWAnvilInv inv = new SWAnvilInv(p, BauSystem.MESSAGE.parse("SPEED_TAB_NAME", p));
        inv.setItem(Material.SUGAR);
        inv.setCallback(s -> p.performCommand("speed " + s));
        inv.open();
        return false;
    }

    @Override
    public Permission permission() {
        return Permission.MEMBER;
    }
}
