/* 
    This file is a part of the SteamWar software.
    
    Copyright (C) 2020  SteamWar.de-Serverteam

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

package de.steamwar.bausystem.commands;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.Permission;
import de.steamwar.bausystem.world.Welt;
import de.steamwar.bausystem.world.regions.GlobalRegion;
import de.steamwar.bausystem.world.regions.Region;
import de.steamwar.command.SWCommand;
import de.steamwar.sql.SchematicNode;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;

import java.io.IOException;
import java.util.logging.Level;

public class CommandReset extends SWCommand {

    public CommandReset() {
        super("reset");
    }

    @Register(help = true)
    public void genericHelp(Player p, String... args) {
        p.sendMessage("§8/§ereset §8- §7Setzte die Region zurück");
        p.sendMessage("§8/§ereset §8[§7Schematic§8] §8- §7Setzte die Region mit einer Schematic zurück");
    }

    @Register
    public void genericResetCommand(Player p) {
        if (!permissionCheck(p)) return;
        Region region = regionCheck(p);
        if (region == null) return;
        try {
            region.reset(null, false);
            p.sendMessage(BauSystem.PREFIX + "§7Region zurückgesetzt");
        } catch (IOException e) {
            p.sendMessage(BauSystem.PREFIX + "§cFehler beim Zurücksetzen der Region");
            Bukkit.getLogger().log(Level.WARNING, "Failed testblock", e);
        }
    }

    @Register
    public void schematicResetCommand(Player p, SchematicNode schem) {
        if (!permissionCheck(p)) return;
        Region region = regionCheck(p);
        if (region == null) return;
        try {
            region.reset(schem, false);
            p.sendMessage(BauSystem.PREFIX + "§7Region zurückgesetzt");
        } catch (IOException e) {
            p.sendMessage(BauSystem.PREFIX + "§cFehler beim Zurücksetzen der Region");
            Bukkit.getLogger().log(Level.WARNING, "Failed reset", e);
        }
    }

    private boolean permissionCheck(Player player) {
        if (Welt.noPermission(player, Permission.WORLD)) {
            player.sendMessage(BauSystem.PREFIX + "§cDu darfst hier nicht die Region zurücksetzen");
            return false;
        }
        return true;
    }

    private Region regionCheck(Player player) {
        Region region = Region.getRegion(player.getLocation());
        if (region == GlobalRegion.getInstance()) {
            player.sendMessage(BauSystem.PREFIX + "§cDu befindest dich derzeit in keiner Region");
            return null;
        }
        return region;
    }
}
