package de.steamwar.misslewars.scripts.implemented;

import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import de.steamwar.misslewars.MissileWars;
import de.steamwar.misslewars.scripts.RunnableScript;
import de.steamwar.misslewars.scripts.RunnableScriptEvent;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public class CooldownScript implements RunnableScript {

    private int cooldown = 0;

    public CooldownScript(JsonObject object) {
        JsonPrimitive primitive = object.getAsJsonPrimitive("cooldown");
        if(primitive.isNumber()) cooldown = primitive.getAsInt();
    }

    @Override
    public boolean execute(RunnableScriptEvent runnableScriptEvent) {
        Material mainHand = runnableScriptEvent.getPlayer().getInventory().getItemInMainHand().getType();
        Material offHand = runnableScriptEvent.getPlayer().getInventory().getItemInOffHand().getType();
        Bukkit.getScheduler().runTaskLater(MissileWars.getPlugin(), () -> {
            if (mainHand != Material.AIR) runnableScriptEvent.getPlayer().setCooldown(mainHand, cooldown);
            if (offHand != Material.AIR) runnableScriptEvent.getPlayer().setCooldown(offHand, cooldown);
        }, 1);
        return true;
    }
}
