/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2023  SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.script;

import de.steamwar.bausystem.utils.FlatteningWrapper;
import de.steamwar.command.SWCommand;
import de.steamwar.linkage.Linked;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

@Linked
public class UnsignCommand extends SWCommand {

    public UnsignCommand() {
        super("unsign");
    }

    @Register(description = "UNSIGN_HELP")
    public void unsignCommand(Player p) {
        ItemStack itemStack = p.getInventory().getItemInMainHand();
        if (FlatteningWrapper.impl.isNoBook(itemStack)) return;
        ItemStack clone = new ItemStack(Material.WRITABLE_BOOK);
        clone.setItemMeta(itemStack.getItemMeta());
        p.getInventory().setItemInMainHand(clone);
    }
}
