/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2020  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem;

import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.List;

public class SWUtils {

    public static void giveItemToPlayer(Player player, ItemStack itemStack) {
        if (itemStack == null || itemStack.getType() == Material.AIR) {
            return;
        }
        for (int i = 0; i < player.getInventory().getSize(); i++) {
            ItemStack current = player.getInventory().getItem(i);
            if (current != null && current.isSimilar(itemStack)) {
                player.getInventory().setItem(i, null);
                itemStack = current;
                break;
            }
        }
        ItemStack current = player.getInventory().getItemInMainHand();
        player.getInventory().setItemInMainHand(itemStack);
        if (current.getType() != Material.AIR) {
            player.getInventory().addItem(current);
        }
    }

    public static List<String> manageList(List<String> strings, String[] args, int index) {
        strings = new ArrayList<>(strings);
        for (int i = strings.size() - 1; i >= 0; i--) {
            if (!strings.get(i).startsWith(args[index])) {
                strings.remove(i);
            }
        }
        return strings;
    }

    public static List<String> manageList(List<String> strings, String[] args) {
        return manageList(strings, args, args.length - 1);
    }

}
