package de.steamwar.lobby.particle.elements;

import de.steamwar.lobby.LobbySystem;
import de.steamwar.lobby.particle.ParticleElement;
import de.steamwar.lobby.particle.ParticleTickData;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerQuitEvent;

import java.util.HashMap;
import java.util.Map;

public class Delayed extends DelegatingParticleElement {

    private DelayedData delayedData = new DelayedData();
    private int interval;

    private static class DelayedData implements Listener {
        private Map<Player, Integer> data = new HashMap<>();

        @EventHandler(ignoreCancelled = true)
        public void onPlayerQuit(PlayerQuitEvent event) {
            data.remove(event.getPlayer());
        }
    }

    public Delayed(ParticleElement particleElement, int interval) {
        super(particleElement);
        Bukkit.getPluginManager().registerEvents(delayedData, LobbySystem.getPlugin());
        this.interval = interval;
        if (interval <= 0) {
            throw new IllegalArgumentException("Interval must be greater than 0");
        }
    }

    @Override
    public String attribute() {
        return null;
    }

    @Override
    public void tick(ParticleTickData particleTickData) {
        int currentNumber = delayedData.data.getOrDefault(particleTickData.getPlayer(), 0) % interval;
        delayedData.data.put(particleTickData.getPlayer(), currentNumber + 1);
        if (currentNumber != 0) {
            return;
        }
        particleElement.tick(particleTickData);
    }
}
