/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2022  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.utils;

import de.steamwar.Reflection;
import de.steamwar.bausystem.features.util.NoClipCommand;
import net.minecraft.nbt.NBTBase;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.nbt.NBTTagList;
import net.minecraft.network.protocol.game.PacketPlayInSetCreativeSlot;
import net.minecraft.network.protocol.game.PacketPlayOutExplosion;
import net.minecraft.network.protocol.game.PacketPlayOutGameStateChange;
import net.minecraft.server.level.PlayerInteractManager;
import net.minecraft.world.level.EnumGamemode;
import org.bukkit.GameMode;
import org.bukkit.Material;
import org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer;
import org.bukkit.craftbukkit.v1_20_R1.inventory.CraftItemStack;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import java.util.List;

public class NMSWrapper20 implements NMSWrapper {

    private static final Reflection.Field<EnumGamemode> playerGameMode = Reflection.getField(PlayerInteractManager.class, EnumGamemode.class, 0);

    @Override
    @SuppressWarnings("deprecation")
    public void setInternalGameMode(Player player, GameMode gameMode) {
        playerGameMode.set(((CraftPlayer) player).getHandle().e, EnumGamemode.a(gameMode.getValue()));
    }

    @Override
    public void setSlotToItemStack(Player player, Object o) {
        PacketPlayInSetCreativeSlot packetPlayInSetCreativeSlot = (PacketPlayInSetCreativeSlot) o;
        int index = packetPlayInSetCreativeSlot.a();
        if (index >= 36 && index <= 44) {
            index -= 36;
        } else if (index > 44) {
            index -= 5;
        } else if (index <= 8) {
            index = index - 8 + 36;
        }
        player.getInventory().setItem(index, CraftItemStack.asBukkitCopy(packetPlayInSetCreativeSlot.c()));
        if (index < 9) player.getInventory().setHeldItemSlot(index);
        player.updateInventory();
    }

    private static final Reflection.Field<PacketPlayOutGameStateChange.a> gameStateChangeReason = Reflection.getField(NoClipCommand.gameStateChange, PacketPlayOutGameStateChange.a.class, 12);

    @Override
    public void setGameStateChangeReason(Object packet) {
        gameStateChangeReason.set(packet, PacketPlayOutGameStateChange.d);
    }

    @Override
    public void setPlayerBuildAbilities(Player player) {
        ((CraftPlayer) player).getHandle().fO().d = true;
        ((CraftPlayer) player).getHandle().fO().e = true;
    }

    @Override
    public Material pathMaterial() {
        return Material.DIRT_PATH;
    }

    private static final int threshold = 2048;

    @Override
    public boolean checkItemStack(ItemStack item) {
        net.minecraft.world.item.ItemStack nmsItem = CraftItemStack.asNMSCopy(item);
        NBTTagCompound tag = nmsItem.v();
        if (tag != null && tag.e("BlockEntityTag")) {
            NBTTagCompound blockTag = tag.p("BlockEntityTag");
            if (blockTag.e("Items")) {
                return drillDown(blockTag.c("Items", 10), 0, 0) > threshold;
            }
        }

        return false;
    }

    private int drillDown(NBTTagList items, int layer, int start) {
        if (layer > 2) return start + threshold;
        int invalid = start;
        for (NBTBase nbtBase : items) {
            if (!(nbtBase instanceof NBTTagCompound))
                continue;
            NBTTagCompound slot = (NBTTagCompound) nbtBase;
            if (slot.e("tag")) {
                invalid += slot.f("Count");
                NBTTagCompound iTag = slot.p("tag");
                if (iTag.e("BlockEntityTag")) {
                    NBTTagCompound blockTag = iTag.p("BlockEntityTag");
                    if (blockTag.e("Items")) {
                        invalid = drillDown(blockTag.c("Items", 10), layer + 1, invalid);
                    }
                }
            }
            if (invalid > threshold)
                break;
        }
        return invalid;
    }

    private final Class<?> explosionPacket = Reflection.getClass("net.minecraft.network.protocol.game.ClientboundExplodePacket");
    private final Reflection.Field<Double> a = Reflection.getField(explosionPacket, double.class, 0);
    private final Reflection.Field<Double> b = Reflection.getField(explosionPacket, double.class, 1);
    private final Reflection.Field<Double> c = Reflection.getField(explosionPacket, double.class, 2);
    private final Reflection.Field<Float> d = Reflection.getField(explosionPacket, float.class, 0);
    private final Reflection.Field<List> e = Reflection.getField(explosionPacket, List.class, 0);

    @Override
    public Object resetExplosionKnockback(Object packet) {
        PacketPlayOutExplosion packetPlayOutExplosion = (PacketPlayOutExplosion) packet;
        return new PacketPlayOutExplosion(a.get(packetPlayOutExplosion), b.get(packetPlayOutExplosion), c.get(packetPlayOutExplosion), d.get(packetPlayOutExplosion), e.get(packetPlayOutExplosion), null);
    }
}
