/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2023  SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.towerrun.winconditions;

import de.steamwar.towerrun.game.TowerRunGame;
import de.steamwar.towerrun.game.TowerRunPlayer;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.entity.PlayerDeathEvent;

public class LastOutsideWincondition extends OutsideWincondition {
    public LastOutsideWincondition() {
        super("LAST_OUTSIDE");
    }

    @Override
    public void onPlayerOutside(Player player) {
        TowerRunPlayer towerRunPlayer = TowerRunPlayer.get(player);
        outside(towerRunPlayer);
        if (TowerRunGame.PLAYERS_ALIVE.isEmpty()) {
            TowerRunGame.win(towerRunPlayer);
        }
    }

    @EventHandler(priority = EventPriority.LOW)
    public void onPlayerDeath(PlayerDeathEvent event) {
        if (TowerRunGame.PLAYERS_ALIVE.isEmpty()) {
            if (TowerRunGame.PLAYERS_ESCAPED.isEmpty()) {
                TowerRunGame.tie();
                return;
            }
            TowerRunGame.win(TowerRunGame.PLAYERS_ESCAPED.get(TowerRunGame.PLAYERS_ESCAPED.size() - 1));
        }
    }
}
