package de.steamwar.lobby.particle.elements;

import de.steamwar.lobby.LobbySystem;
import de.steamwar.lobby.particle.ParticleElement;
import de.steamwar.lobby.particle.ParticleEnum;
import de.steamwar.lobby.particle.ParticleTickData;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public class RandomParticle implements ParticleElement {

    private RandomData randomData;
    private ParticleEnum[] particleEnums;

    private static class RandomData implements Listener {
        private Random random = new Random();
        private int max;
        private Map<Player, Integer> data = new HashMap<>();

        public RandomData(int max) {
            this.max = max;
        }

        @EventHandler(ignoreCancelled = true)
        public void onPlayerJoin(PlayerJoinEvent event) {
            data.put(event.getPlayer(), random.nextInt(max));
        }

        @EventHandler(ignoreCancelled = true)
        public void onPlayerQuit(PlayerQuitEvent event) {
            data.remove(event.getPlayer());
        }
    }

    public RandomParticle(ParticleEnum... particleEnums) {
        if (particleEnums.length == 0) {
            throw new IllegalArgumentException("ParticleEnums must not be empty");
        }
        this.randomData = new RandomData(particleEnums.length);
        Bukkit.getPluginManager().registerEvents(randomData, LobbySystem.getPlugin());
        this.particleEnums = particleEnums;
    }

    @Override
    public void tick(ParticleTickData particleTickData) {
        int currentNumber = randomData.data.getOrDefault(particleTickData.getPlayer(), 0);
        particleEnums[currentNumber].getParticle().getParticleElement().tick(particleTickData);
    }
}
