/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2021  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.slaves.panzern.algorithms;

import de.steamwar.bausystem.features.slaves.panzern.PanzernAlgorithm;
import de.steamwar.bausystem.features.slaves.panzern.PanzernResult;
import de.steamwar.linkage.Linked;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.block.data.AnaloguePowerable;
import org.bukkit.block.data.Directional;
import org.bukkit.block.data.Powerable;
import org.bukkit.block.data.type.RedstoneWire;

import java.util.Map;
import java.util.Set;

@Linked
public class PowerableActivation implements PanzernAlgorithm {

    @Override
    public PanzernResult check(Block source, Map<BlockFace, Block> adjacent, Set<Material> adjacentMaterials) {
        int powered = 0;
        int powerable = 0;
        for (BlockFace blockFace : BLOCK_FACES) {
            if (!adjacent.containsKey(blockFace)) {
                continue;
            }
            Block block = adjacent.get(blockFace);
            if ((block.getType() == Material.HOPPER || block.getBlockData() instanceof Powerable || block.getBlockData() instanceof AnaloguePowerable) && block.getType() != Material.OBSERVER) {
                powerable++;
            }
            if (block.getType() == Material.TNT) {
                powerable++;
            }
            if (blockFace == BlockFace.DOWN) {
                for (BlockFace otherBlockFace : HORIZONTAL_FACES) {
                    Block otherBlock = block.getRelative(otherBlockFace);
                    if (otherBlock.getType() == Material.PISTON) {
                        powered++;
                    }
                }
            }
            if (blockFace == BlockFace.UP) {
                continue;
            }
            switch (block.getType()) {
                case REDSTONE_WIRE:
                    RedstoneWire redstoneWire = (RedstoneWire) block.getBlockData();
                    boolean dot = true;
                    for (BlockFace current : HORIZONTAL_FACES) {
                        dot &= redstoneWire.getFace(current) == RedstoneWire.Connection.NONE;
                    }
                    if (dot) {
                        powered++;
                    } else if (redstoneWire.getAllowedFaces().contains(blockFace)) {
                        if (redstoneWire.getFace(blockFace) == RedstoneWire.Connection.SIDE) {
                            powered++;
                        }
                    }
                    break;
                case REPEATER:
                case COMPARATOR:
                case OBSERVER:
                    if (((Directional) block.getBlockData()).getFacing() == blockFace) {
                        powered++;
                    }
                    break;
                default:
                    break;
            }
        }
        if (powered <= 1 && powerable <= 1) {
            return PanzernResult.DEFAULT;
        }
        return PanzernResult.SLAB;
    }
}
