/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2022  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.util.items;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.Permission;
import de.steamwar.bausystem.linkage.specific.BauGuiItem;
import de.steamwar.inventory.SWItem;
import de.steamwar.linkage.Linked;
import org.bukkit.GameMode;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.ClickType;
import org.bukkit.inventory.ItemStack;

import java.util.Arrays;

@Linked
public class GamemodeBauGuiItem extends BauGuiItem {

    public GamemodeBauGuiItem() {
        super(31);
    }

    @Override
    public ItemStack getItem(Player player) {
        return new SWItem(Material.BARRIER, BauSystem.MESSAGE.parse("OTHER_ITEMS_GAMEMODE_NAME", player), Arrays.asList(BauSystem.MESSAGE.parse("OTHER_ITEMS_GAMEMODE_LORE_1", player), BauSystem.MESSAGE.parse("OTHER_ITEMS_GAMEMODE_LORE_2", player)), false, clickType -> {}).getItemStack();
    }

    @Override
    public boolean click(ClickType click, Player p) {
        p.closeInventory();
        GameMode gameMode = p.getGameMode();
        if (click.isRightClick()) {
            if (gameMode != GameMode.CREATIVE) {
                p.setGameMode(GameMode.CREATIVE);
            } else {
                p.setGameMode(GameMode.SPECTATOR);
            }
        } else if (click.isLeftClick()) {
            if (gameMode != GameMode.SURVIVAL) {
                p.setGameMode(GameMode.SURVIVAL);
            } else {
                p.setGameMode(GameMode.ADVENTURE);
            }
        }
        return false;
    }

    @Override
    public Permission permission() {
        return Permission.MEMBER;
    }
}
