/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2022  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.util;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.command.SWCommand;
import de.steamwar.linkage.Linked;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;

import java.util.HashSet;
import java.util.Set;

@Linked
public class DeclutterCommand extends SWCommand {

    public DeclutterCommand() {
        super("declutter", "cleanup");
    }

    @Register(description = "OTHER_DECLUTTER_HELP")
    public void genericCommand(Player p) {
        Inventory inventory = p.getInventory();
        Set<ItemStack> containedItems = new HashSet<>();
        inventory.forEach(itemStack -> {
            if (itemStack == null) {
                return;
            }

            if (containedItems.stream().anyMatch(itemStack::isSimilar)) {
                itemStack.setAmount(0);
                return;
            }

            if (itemStack.getAmount() > 1) {
                itemStack.setAmount(1);
            }

            containedItems.add(itemStack);
        });

        BauSystem.MESSAGE.send("OTHER_DECLUTTER_DONE", p);
    }
}
