/* 
    This file is a part of the SteamWar software.
    
    Copyright (C) 2020  SteamWar.de-Serverteam

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

package de.steamwar.bausystem.world;

import de.steamwar.bausystem.BauSystem;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerMoveEvent;

public class AFKStopper implements Listener {

    private static final String afkWarning = BauSystem.PREFIX + "§cDieser Server wird bei weiterer Inaktivität in einer Minute gestoppt";

    private int minutesAfk;

    public AFKStopper() {
        minutesAfk = 0;
        Bukkit.getPluginManager().registerEvents(this, BauSystem.getPlugin());
        Bukkit.getScheduler().runTaskTimer(BauSystem.getPlugin(), () -> {
            switch (minutesAfk) {
                case 5:
                    for (Player p : Bukkit.getOnlinePlayers())
                        p.kickPlayer("§cAuf diesem Server ist seit 5 Minuten nichts passiert.");
                    break;
                case 4:
                    Bukkit.broadcastMessage(afkWarning);
                default:
                    minutesAfk++;
            }
        }, 1200, 1200); //every minute
    }

    @EventHandler
    public void onPlayerMove(PlayerMoveEvent event) {
        minutesAfk = 0;
    }
}
